---
name: Build Pull Request Package

on:
  pull_request:
    branches:
      - current
      - crux
      - equuleus

jobs:
  j2lint:
    name: Validate j2 files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2
      - name: Setup J2Lint
        timeout-minutes: 2
        run: |
          sudo pip install git+https://github.com/aristanetworks/j2lint.git@341b5d5db86e095b622f09770cb6367a1583620e
      - name: Run J2lint
        timeout-minutes: 2
        run: |
          j2lint $GITHUB_WORKSPACE/data
