---
name: Check pull request message format

on:
  pull_request:
    branches:
      - current
      - crux
      - equuleus

jobs:
  check-pr-title:
    name: Check pull request title
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2
      - name: Install the requests library
        run: pip3 install requests
      - name: Check the PR title
        timeout-minutes: 2
        run: |
          ./scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}'
